"""Generate a one-click installer for a new PC.

Produces one self-contained PowerShell script. Carry it to the office PC,
right-click -> Run with PowerShell, and it does everything: app, runtime, seed
database, shared-DB credentials.

  python cloud_test/make_installer.py            -> cloud_test/install_office.ps1
  python cloud_test/make_installer.py --out D:\\install_office.ps1

The seed is fetched over a public Drive link, so the installer carries no Google
credentials and nothing in it expires. It does carry the Turso auth token, which
is write access to the shared picks database — keep the file to yourself and
delete it from the target PC after installing.

Prerequisite (once):  python cloud_test/drive_sync.py share seed.db.gz
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DRIVE_STATE = HERE / "drive_state.json"
TURSO = HERE / "turso.json"
SEED_NAME = "seed.db.gz"
DEFAULT_OUT = HERE / "install_office.ps1"
APP_DIR = r"C:\AI\Open_Vending"
REPO_ZIP = "https://github.com/liewcc/Open_Vending/archive/refs/heads/main.zip"

TEMPLATE = r"""# Open Vending - one-click install for a new PC.
# Generated by cloud_test/make_installer.py.
# Contains the shared-database token - delete this file after installing.
$ErrorActionPreference = 'Stop'

$AppDir     = '{app_dir}'
$RepoZip    = '{repo_zip}'
$SeedUrl    = '{seed_url}'
$TursoUrl   = '{turso_url}'
$TursoToken = '{turso_token}'

function Step($n, $msg) {{ Write-Host ('  [{{0}}/5] {{1}}' -f $n, $msg) -ForegroundColor Cyan }}

Write-Host ''
Write-Host '  ============================================'
Write-Host '   Open Vending - new PC setup'
Write-Host '  ============================================'
Write-Host ''

# 1 - app source ---------------------------------------------------------------
Step 1 'Downloading the app...'
$tmp = Join-Path $env:TEMP ('ov-install-' + (Get-Random))
New-Item -ItemType Directory -Force -Path $tmp | Out-Null
$zip = Join-Path $tmp 'app.zip'
Invoke-WebRequest -Uri $RepoZip -OutFile $zip -UseBasicParsing
Expand-Archive -Path $zip -DestinationPath $tmp -Force
$src = (Get-ChildItem -Path $tmp -Directory | Select-Object -First 1).FullName
New-Item -ItemType Directory -Force -Path $AppDir | Out-Null
Copy-Item (Join-Path $src '*') $AppDir -Recurse -Force
Write-Host '        app files in place'

# 2 - runtime (python, node, chromium, electron) -------------------------------
Step 2 'Installing the runtime (several minutes, about 300MB)...'
# Start-Process with an explicit path and working directory: passing the batch
# file through `cmd.exe /c` fails here, PowerShell mangles the quoted argument
# and cmd reports 'setup.bat is not recognized'.
$setup = Join-Path $AppDir 'setup.bat'
Start-Process -FilePath $setup -WorkingDirectory $AppDir -Wait -NoNewWindow
if (-not (Test-Path (Join-Path $AppDir 'python\python.exe'))) {{
  throw 'setup.bat did not produce python - check setup.log in the app folder'
}}
Write-Host '        runtime ready'

# 3 - seed database (public link, no sign-in) ----------------------------------
Step 3 'Downloading the seed database (about 47MB)...'
$dbDir = Join-Path $AppDir 'db'
New-Item -ItemType Directory -Force -Path $dbDir | Out-Null
$gz = Join-Path $dbDir 'seed.db.gz'
Invoke-WebRequest -Uri $SeedUrl -OutFile $gz -UseBasicParsing
$head = [System.IO.File]::ReadAllBytes($gz)[0..1]
if ($head[0] -ne 0x1f -or $head[1] -ne 0x8b) {{
  throw 'The seed download was not a gzip file - the share link may have been revoked.'
}}

Write-Host '        expanding...'
$out = Join-Path $dbDir 'vending.db'
$in  = [System.IO.File]::OpenRead($gz)
$gzs = New-Object System.IO.Compression.GZipStream($in, [System.IO.Compression.CompressionMode]::Decompress)
$dst = [System.IO.File]::Create($out)
$gzs.CopyTo($dst)
$dst.Close(); $gzs.Close(); $in.Close()
Remove-Item $gz -Force
$mb = [math]::Round((Get-Item $out).Length / 1MB, 1)
Write-Host ('        vending.db ready (' + $mb + ' MB)')

# 4 - shared database credentials ----------------------------------------------
Step 4 'Configuring the shared database...'
$cfgDir = Join-Path $env:APPDATA 'open-vending'
New-Item -ItemType Directory -Force -Path $cfgDir | Out-Null
$cfgFile = Join-Path $cfgDir 'settings.json'
$cfg = @{{}}
if (Test-Path $cfgFile) {{
  try {{
    (Get-Content $cfgFile -Raw | ConvertFrom-Json).PSObject.Properties | ForEach-Object {{ $cfg[$_.Name] = $_.Value }}
  }} catch {{ }}
}}
$cfg['remoteUrl']   = $TursoUrl
$cfg['remoteToken'] = $TursoToken
$cfg | ConvertTo-Json -Compress | Set-Content $cfgFile -Encoding utf8
Write-Host '        picks and buffers will use the shared database'

# 5 - done ----------------------------------------------------------------------
Step 5 'Cleaning up...'
Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue
Write-Host ''
Write-Host '  Done.' -ForegroundColor Green
Write-Host ('  Launch with:  ' + $AppDir + '\run.bat')
Write-Host ''
Write-Host '  Delete this installer - it contains the shared-database token.' -ForegroundColor Yellow
Write-Host ''
"""


def main():
    out = Path(sys.argv[sys.argv.index("--out") + 1]) if "--out" in sys.argv else DEFAULT_OUT

    if not TURSO.exists():
        sys.exit("missing {} - the Turso url and token".format(TURSO))
    turso = json.loads(TURSO.read_text(encoding="utf-8"))

    if not DRIVE_STATE.exists():
        sys.exit("missing {} - run: python cloud_test/drive_sync.py init".format(DRIVE_STATE))
    seed_url = json.loads(DRIVE_STATE.read_text(encoding="utf-8")) \
        .get("public", {}).get(SEED_NAME)
    if not seed_url:
        sys.exit("{} has no public link yet - run: "
                 "python cloud_test/drive_sync.py share {}".format(SEED_NAME, SEED_NAME))

    out.write_text(TEMPLATE.format(
        app_dir=APP_DIR,
        repo_zip=REPO_ZIP,
        seed_url=seed_url,
        turso_url=turso["url"],
        turso_token=turso["token"],
    ), encoding="utf-8")

    print("wrote {}".format(out))
    print("  seed       public link, no sign-in, nothing expires")
    print("  shared DB  {}".format(turso["url"].split("//")[-1]))
    print("  installs   {}".format(APP_DIR))
    print("\nCarry this one file to the office PC, right-click -> Run with PowerShell.")
    print("It contains the shared-database token - delete it after installing.")


if __name__ == "__main__":
    main()
